#!/bin/sh
# Copyright (c) YAPP contributors
# SPDX-License-Identifier: MIT

dir=$1
shift
case "$dir" in
""|".") dir="" ;;
*) dir="$dir/" ;;
esac
${CXX} ${INCLUDE} -MM -MG "$@" | sed -e "s@\(.*\)\.o:@$dir\1.o $dir\1.d:@"
